### ISSUE TITLE
[feature request] Analytical Optimized Engine rebalance

### ISSUE THREAD

**Issue by JinHai-CN** [matrixorigin/matrixone#1055]
Analytical Optimized Engine with columnar storage layout is used for OLAP applications. To support horizontal scalability, both CUBE / CUBE Driver in Matrixone and AOE need to support raft group split, state machine snapshot and data migration.

Following issues are related to this feature.

- [x] Shared log: #677 

- [x] AOE storage split: #744 

- [x] CUBE support split: matrixorigin/matrixcube#248

- [x] AOE storage snapshot: #170 

- [x] CUBE Snapshot support: serialize raft-group state: matrixorigin/matrixcube#322

- [x] CUBE Snapshot support: transfer serialized state: matrixorigin/matrixcube#323

- [x] CUBE Snapshot support: deserialized raft-group state: matrixorigin/matrixcube#321

- [ ] CUBE Snapshot support: Tuning: matrixorigin/matrixcube#324

- [x] Log compaction: matrixorigin/matrixcube#320

**Comment by JinHai-CN** [comment]
matrixorigin/matrixcube#324 will be done in v0.3.0
