### ISSUE TITLE
[feature request] Support expression, type and functions

### ISSUE THREAD

**Issue by JinHai-CN** [matrixorigin/matrixone#1059]
- [x] support plus/div/minus/mult/mod for two different types, #736 
- [x] support correct select result for condition 'int div int', #789 
- [x] support Not and ! operator, #782 
- [x] more expression supporting for insert, #825
- [x] support type DATE, DATETIME, #827 
- [x] float precision performance adapt to mysql, #894 
- [x] support like and where in show-statement, #979

**Comment by JinHai-CN** [comment]
all done.
