### ISSUE TITLE
[Subtask] Implement real-time pipeline

### ISSUE THREAD

**Issue by gavinyue** [matrixorigin/matrixone#10975]
## What is Pipeline? 
Streaming Data Pipeline is a process that continuously ingest the events from Source and transform/process to make the events useful and export into the destination. 

Someplace, may refer pipeline as persisted_query

## Connectors are pre-created Pipeline Template

MO Connectors are pre-created pipeline template that can be used to quickly launch the pipeline that copies data from Source  to MO or from MO to Sink.

## How users to create Pipeline 
Except using Connectors, the first support syntax would be 

`
   Create StreamA As Select From StreamB 
`
This way would create a pipeline that read events from StreamB and write events to StreamA. 

Use SQL to define a Pipeline.

## Tasks

- [ ] Design pipeline data structure
- [ ] Design and implement the storage that hold pipeline instances
- [ ] Implement the Manager that can CRUD the pipeline instances
- [ ] Support Connectors Management
- [ ] https://github.com/matrixorigin/matrixone/issues/10974
- [ ] #10977

**Comment by gavinyue** [comment]
since we use the table for stream, so this could be considered as COMPLETED
