### ISSUE TITLE
[Feature Request]: Umbrella issue of refactor csv reader

### ISSUE THREAD

**Issue by ouyuanning** [matrixorigin/matrixone#13390]
### Why do you want to refactor this code?

```Markdown
目前csv reader有几个问题需要解决
1、与MySQL兼容性问题。比如：什么情况下是Null
2、csv并行的切割问题。目前只是根据\n切割，而当列中有换行符的时候，这个切割就会搓掉
```

### Describe the solution you'd like

重写csv reader及csv切割相关代码，保持与MySQL兼容的同时，保证切割的准确性。

相关issue：
- [ ] https://github.com/matrixorigin/MO-Cloud/issues/1583
- [ ] https://github.com/matrixorigin/MO-Cloud/issues/1527
- [ ] https://github.com/matrixorigin/MO-Cloud/issues/2149
- [ ] https://github.com/matrixorigin/MO-Cloud/issues/2230

**Comment by noorall** [comment]
暂未处理

**Comment by dengn** [comment]
@yangj1211 @aressu1985 the objective of this feature is to be fully mysql compatible with csv loading.

**Comment by LiSong0214** [comment]
https://github.com/matrixorigin/docs/blob/yanglei/csvReader/design/mo/sql/20240110-yanglei-csvReaderRefactor.md#23-mysql-%E4%B8%8E-mo%E9%BB%98%E8%AE%A4%E8%A1%8C%E4%B8%BA

**Comment by ouyuanning** [comment]
待并行切割的PR合并后关闭

**Comment by ouyuanning** [comment]
相关issue已关闭
