### ISSUE TITLE
[Subtask]: detect and merge OR-expressions into IN-expression

### ISSUE THREAD

**Issue by aunjgr** [matrixorigin/matrixone#15463]
### Parent Issue

#14469

### Detail of Subtask

* [ ] a = 1 OR a = 2 OR a = 3 => a IN (1, 2, 3)
* [ ] (a = 1 AND b = 2) OR (a = 3 AND b = 4) => composed_key IN (serial(1, 2), serial(3, 4)) if (a, b) is a composed primary key
* [ ] (a = 1 AND b = 2) OR (a = 3 AND b = 4 AND c = 5) => composed_key PREFIX_EQ serial(1, 2) OR composed_key = serial(3, 4, 5) => composed_key PREFIX_IN (serial(1, 2), serial(3, 4)) if (a, b, c) is a composed primary key
