### ISSUE TITLE
[Subtask]: Performance analysis and hardware selection test of logservice

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#8593]
### Parent Issue

#8592

### Detail of Subtask

As the previous discussion, we want basic hardware recommendations for `log service` with an illustration of the relationship between performance and hardware.

- [ ] Provide a specific resource utilization model of `log service`.
- [ ] Design a test matrix of workload and hardware specifications and run each combination.
- [ ] Provide basic hardware recommendations or principle.
