### ISSUE TITLE
[Subtask]:  Performance analysis and hardware selection test of DN

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#8594]
### Parent Issue

#8592

### Detail of Subtask

we want basic hardware recommendations for dn service with an illustration of the relationship between performance and hardware.

- [ ] Provide a specific resource utilization model of dn service.
- [ ] Design a test matrix of workload and hardware specifications and run each combination.
- [ ] Provide basic hardware recommendations or principles.
