### ISSUE TITLE
[Subtask]: Performance analysis and hardware selection test of CN

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#8595]
### Parent Issue

#8592

### Detail of Subtask

we want basic hardware recommendations for cn service with an illustration of the relationship between performance and hardware.

- [ ]  Provide a specific resource utilization model of cn service.
- [ ]  Design a test matrix of workload and hardware specifications and run each combination.
- [ ]  Provide basic hardware recommendations or principles.

**Comment by nnsgmsone** [comment]
等处理完https://github.com/matrixorigin/matrixone/issues/7891%E5%90%8E%E5%86%8D%E5%A4%84%E7%90%86%E8%BF%99%E4%B8%AA%EF%BC%8C
